# Generated by Django 4.2.7 on 2023-12-05 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=750)),
                ('subtitle', models.CharField(max_length=750)),
                ('authors', models.CharField(max_length=750)),
                ('publisher', models.CharField(max_length=750)),
                ('category', models.CharField(max_length=100)),
                ('published_date', models.CharField(max_length=8)),
                ('page_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('print_type', models.CharField(max_length=10)),
                ('dust_jacket', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('binding', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='photos', to='books.bookimage'),
        ),
    ]
