# Generated by Django 4.2.7 on 2023-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(null=True, related_name='photos', to='books.bookimage'),
        ),
    ]
