# Generated by Django 4.2.7 on 2023-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_images_alter_bookimage_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='bookid',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
