# Generated by Django 4.2.7 on 2023-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_height_alter_book_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='thickness',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='width',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
