# Generated by Django 4.2.7 on 2023-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_height_alter_book_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
