# Generated by Django 4.2.7 on 2023-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_isbn_10_book_isbn_13_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookid',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
